Add text language selection
taehoio/youtube2notion pull request #13
Opened 2021-08-08 10:51 UTC by gnokoheat

It can be select to text language want to display with the input parameter.

### new input parameter

- text_language `ex) ko, ja, de ...`

### language selection priority

1. Select subtitles of the language of input parameter.
2. If there is no subtitles in the language of the input parameter, translate English subtitles.
3. If there is no subtitles in the language of the input parameter and English subtitles, Translate the automatically translated subtitles to input parameter language.

### notion page title changed

- VIDEO_ID + TEXT_LANGUAGE `ex) EWbGahsxXK4 => EWbGahsxXK4(ko)`

2021-08-08 11:29 UTC, xissy requested changes
1. didn't get a sense on the changes you suggesting in `get_subtitle_elements()` function. would you please have some further explanation?
2. nit; sorry to be a grammar police, how about `SUBTITLE_LANGUAGE` rather than `TEXT_LANGUAGE`? TEXT_LANGUAGE doesn't sound good in english to me. :)
3. it would be great if we have test cases for newly added codes. it also helps make reviewers understand your intentions.

2021-08-08 11:29 UTC, xissy commented on README.md
> +docker run --rm -it taehoio/youtube2notion youtube2notion.py YOUTUBE_VIDEO_ID -t NOTION_TOKEN_V2 -p NOTION_PAGE_ID -l TEXT_LANGUAGE
```suggestion
docker run --rm -it taehoio/youtube2notion youtube2notion.py YOUTUBE_VIDEO_ID -t NOTION_TOKEN_V2 -p NOTION_PAGE_ID -l SUBTITLE_LANGUAGE
```

2021-08-08 11:29 UTC, xissy commented on README.md
> +    "text_language": "TEXT_LANGUAGE"
```suggestion
    "subtitle_language": "SUBTITLE_LANGUAGE"
```

2021-08-08 11:29 UTC, xissy commented on app.py
> +    text_language = req.get('text_language')
```suggestion
    subtitle_language = req.get('subtitle_language')
```

2021-08-08 11:29 UTC, xissy commented on README.md
> +    "notion_page_url": "NOTION_PAGE_ID",
```suggestion
    "notion_page_url": "NOTION_PAGE_URL",
```
looks like my bad here. suggesting `notion_page_url` value name as intended.

2021-08-08 11:29 UTC, xissy commented on youtube2notion.py
> +def youtube2notion(video_id: str, output_dir, notion_token_v2, notion_page_url, text_language):
```suggestion
@click.option(
    '--subtitle_language', '-l', 'subtitle_language', required=False, type=str)
def youtube2notion(video_id: str, output_dir, notion_token_v2, notion_page_url, subtitle_language):
```

2021-08-08 11:29 UTC, xissy commented on youtube2notion/youtube2notion.py
> +        self.text_language = text_language
```suggestion
        self.subtitle_language = subtitle_language
```

2021-08-08 11:29 UTC, xissy commented on youtube2notion/youtube2notion.py
> +                 text_language: str = 'ko'):
```suggestion
                 subtitle_language: str = 'ko'):
```

2021-08-08 11:29 UTC, xissy commented on youtube2notion/youtube2notion.py
> +        return YoutubeSubtitle.get_subtitle_elements(self.video_id, [self.text_language, 'en'])
```suggestion
        return YoutubeSubtitle.get_subtitle_elements(self.video_id, [self.subtitle_language, 'en'])
```

2021-08-08 11:29 UTC, xissy commented on youtube2notion/youtube2notion.py
> +            new_page = page.children.add_new(PageBlock, title=self.video_id + '(' + self.text_language + ')')
```suggestion
            new_page = page.children.add_new(PageBlock, title=self.video_id + '(' + self.subtitle_language + ')')
```

2021-08-08 11:29 UTC, xissy commented on youtube2notion/youtube2notion.py
> +            title=self.video_id + '(' + self.text_language + ')',
```suggestion
            title=self.video_id + '(' + self.subtitle_language + ')',
```

2021-08-08 11:29 UTC, xissy commented on youtube2notion/youtube_subtitle.py
> +            transcript_result = transcript.translate(languages[0]).fetch()
could you please why you added those lines? my intention for `get_subtitle_elements()` function was getting a subtitle by the `languages` parameter that indicates language candidates for a representative subtitle language.

2021-08-08 11:39 UTC, xissy commented
제 작은 의견들 달아봤습니다. 영어 표현으로 이해가 부족한 부분이 있으면 언제든 한글로 물어봐 주셔도 좋습니다. PR desc의 내용이 코드에 제대로 표현되지 않은거 같아 부연 설명이나 테스트 코드 등을 요청드렸습니다. 하지만 부담드리고 싶지는 않아 lint와 test 통과만 되면 제가 PR의 의도를 제대로 이해한 후 코드의 함수명이나 자료구조 이름 등을 적절히 표현하는 PR을 보내볼까 합니다.

2021-08-08 12:57 UTC, gnokoheat commented on youtube2notion/youtube_subtitle.py
> +            transcript_result = transcript.translate(languages[0]).fetch()
https://github.com/taehoio/youtube2notion/blob/fb4944058cd6932ee648dd482c77304cedbf4fba/youtube2notion/youtube_subtitle.py#L30

기존의 코드와 같이 `get_transcript` 메소드를 사용하면 `MANUALLY CREATED`, `GENERATED` 에서 list 의 언어를 못가져오는 경우에 error 가 발생하게 됩니다.
예시는 `GENERATED  : ko` 만 있기때문에 에러가 발생하는 케이스 입니다.
```
video_id = "PAZWzt62gH0"
languages = ['ja', 'en']

transcript = YouTubeTranscriptApi().get_transcript(video_id, languages)
```
```
(MANUALLY CREATED)
None

(GENERATED)
 - ko ("한국어 (자동 생성됨)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
...
 - ja ("일본어")
 - jv ("자바어")
 ...
If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
 ```
그래서 `list_transcripts` 메소드로 가능한 언어별 subtitles 을 가져온 뒤에
위와 같은 케이스라면 loop 문에서 `ja` 또는 `en` 이 있는지 찾아서
1. `ja` 가 있는 경우에는 바로 해당 스크립트를 리턴
2. `ja` 가 없고 `en` 만 있는 경우에는 `en` 을 `ja` 로 번역해서 리턴
    (영어가 그나마 다른 모든언어와 대응이 나쁘지 않다고 생각해서)
3. 둘다 없는 경우에는 마지막에 자동생성된 `ko` 를 `ja` 로 번역해서 리턴

으로 처리하도록 위와같은 코드를 작성해 봤습니다.

사실 깊게 고민하고 작성한 코드가 아닌지라 .. 부족한 부분은 의견 또는 수정 부탁 드리고요..
테스트 케이스의 아예 없는 언어 `aa` 가 들어오는 경우에 대해서는 예외처리 해야겠네요.
테스트 케이스 추가에 대한 부분도 고민 해보겠습니다!

2021-08-09 07:39 UTC, xissy approved these changes
요구사항 반영하고 가독성 올리고 테스트 수정 등 자잘한 개선을 해보았습니다. 살펴봐 주세요. 🙏

2021-08-09 11:38 UTC, gnokoheat reviewed
코드를 간결하게 잘 정리해주셔서 감사합니다 또한 원하는바대로 잘 동작하는 것으로 확인됩니다 👍

2021-08-09 11:42 UTC, merged